### 查询课程信息
POST {{gateway_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}

### 查询课程分类
GET {{content_host}}/content/course-category/tree-nodes

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 10,
  "originalPrice":100,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "javaEE",
  "pic": "jaoifwhjop",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "gsegseg",
  "grade": "204001",
  "description": "java网络编程高级java网络编程高级java网络编程高级java网络编程高级"
}


### 课程查询
GET {{content_host}}/content/course/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmciXSwidXNlcl9uYW1lIjoiemhhbmdzYW4iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNzAwNzA4NDExLCJhdXRob3JpdGllcyI6WyJwMSJdLCJqdGkiOiJmMjA2YTM0Zi0yNWI5LTQwNTMtYmVkMy1mMmVkNWExNTZjY2YiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.dt1AavmYESdYxR23hyb6OT4Vhkaedf0nF7kA4VBx-uc

### 查询某个课程的课程计划
GET {{content_host}}/content/teachplan/121/tree-nodes


### 新增课程计划--章
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId" : 74,
  "parentid": 0,
  "grade" : 1,
  "pname" : "新章名称 [点击修改]"
}

###师资管理查询
GET {{content_host}}/content/courseTeacher/list/{id}

### 通过网关课程查询
GET {{gateway_host}}/content/course/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmciXSwidXNlcl9uYW1lIjoie1wiY29tcGFueUlkXCI6XCIxMjMyMTQxNDI1XCIsXCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJpZFwiOlwiNTJcIixcIm5hbWVcIjpcIk3ogIHluIhcIixcInNleFwiOlwiMVwiLFwic3RhdHVzXCI6XCJcIixcInVzZXJuYW1lXCI6XCJ0MVwiLFwidXR5cGVcIjpcIjEwMTAwMlwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3MDA3MTE2OTUsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiZGQzNTNkN2EtNmY2NS00ZGEwLTg1MzctMGQzYTA3ODU0MTU1IiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.piPg3i4plz-2h_ncTWgCsZm-VKZfvW-UHg3dGDyCnug


### 查询课程发布信息
GET {{content_host}}/content/r/coursepublish/136

###
GET {{content_host}}/course/whole/120